name: Deploy Sanity Studio to Cloudflare Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
      - uses: actions/checkout@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: |
        npm i
        npm run build
        wrangler pages publish dist/

  # deploy:
  #   runs-on: ubuntu-latest
  #   name: Deploy
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Publish
  #       uses: cloudflare/wrangler-action@2.0.0
  #       with:
  #         apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  #       run: |
  #         npm i
  #         npm run build
  #         wrangler pages publish dist/