name: Deploy Sanity Studio to Cloudflare Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
            npm ci
            npm run build
      
        uses: cloudflare/wrangler-action@2.0.0
      - name: Publish
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            pages publish dist --project-name=sanity-studio